#!/usr/bin/env node

var log = console.log;
require('look').start()

// #########################################################################################################
njs_path                  = require( 'path' );
njs_fs                    = require( 'fs' );
njs_cp                    = require( 'child_process' );
// .........................................................................................................
require( 'app-module-path' ).addPath( '/vagrant' );

// .........................................................................................................
var cmd = njs_path.join( __dirname, 'build' );
log( cmd );
njs_cp.exec( cmd, function ( error, stdout, stderr ) {
  if ( error ) { throw error }
  if ( stderr && stderr.length > 0 ) { throw new Error( stderr ) };
  log( stdout );
  // .......................................................................................................
  var cmd = njs_path.join( __dirname, '../soba-server/build' );
  log( cmd );
  njs_cp.exec( cmd, function ( error, stdout, stderr ) {
    if ( error ) { throw error }
    if ( stderr && stderr.length > 0 ) { throw new Error( stderr ) };
    log( stdout );
    // .....................................................................................................
    process.argv.push( 'serve' );
    require( './lib/main' );
})
})
