#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR


coffee --watch --output lib --compile src 2>&1 &     																\
  supervisor                                                                        \
    --harmony                                                                       \
    -q                                                                              \
    --no-restart-on error                                                           \
    --watch node_modules,lib,/tmp/inode-bridge.txt                                  \
    --extensions js,coffee,html,json,css,styl                                       \
    lib/main.js





