// Generated by CoffeeScript 1.8.0

/*
#===========================================================================================================



888      8888888888 888     888 8888888888 888         .d8888b.  8888888888 8888888b.  888     888 8888888888 8888888b.
888      888        888     888 888        888        d88P  Y88b 888        888   Y88b 888     888 888        888   Y88b
888      888        888     888 888        888        Y88b.      888        888    888 888     888 888        888    888
888      8888888    Y88b   d88P 8888888    888         "Y888b.   8888888    888   d88P Y88b   d88P 8888888    888   d88P
888      888         Y88b d88P  888        888            "Y88b. 888        8888888P"   Y88b d88P  888        8888888P"
888      888          Y88o88P   888        888              "888 888        888 T88b     Y88o88P   888        888 T88b
888      888           Y888P    888        888        Y88b  d88P 888        888  T88b     Y888P    888        888  T88b
88888888 8888888888     Y8P     8888888888 88888888    "Y8888P"  8888888888 888   T88b     Y8P     8888888888 888   T88b



#===========================================================================================================
 */

(function() {
  var $, D, SBLVL, SOBA, TEXT, TRM, TYPES, alert, badge, db_route, debug, help, info, new_db, range, rmrf, rpr, urge, warn, whisper,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  TEXT = require('coffeenode-text');

  TYPES = require('coffeenode-types');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'soba-level-server';

  info = TRM.get_logger('info', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  urge = TRM.get_logger('urge', badge);

  whisper = TRM.get_logger('whisper', badge);

  help = TRM.get_logger('help', badge);

  SOBA = require('soba-server');

  new_db = require('level');

  range = require('level-range');


  /* https://github.com/loveencounterflow/pipedreams */

  D = require('pipedreams');

  $ = D.remit.bind(D);

  rmrf = require('rimraf');

  this.new_db = function(db_route) {

    /* TAINT make configurable */
    var R, db, sb;
    sb = SOBA.new_server();
    db = new_db(db_route);
    R = {
      '~isa': 'SOBA-LEVEL/db',
      '%soba-server': sb,
      '%level-db': db
    };
    return R;
  };

  this.get_socket_router = function(me) {
    return SOBA.get_router(me['%soba-server']);
  };

  this.get_app = function(me) {
    return SOBA.get_app(me['%soba-server']);
  };

  this.get_sio_server = function(me) {
    return SOBA.get_sio_server(me['%soba-server']);
  };

  this.get_soba_server = function(me) {
    return me['%soba-server'];
  };

  this.get_level_db = function(me) {
    return me['%level-db'];
  };

  this.get_level_db_route = function(me) {
    return (this.get_level_db(me))['location'];
  };

  this.serve = function() {
    var server;
    return server = server.listen(port, function() {
      var host, port, _ref;
      help("server process running on Node v" + process.versions['node']);
      _ref = server.address(), host = _ref.address, port = _ref.port;
      return help("ソバ Server listening to http://" + host + ":" + port);
    });
  };


  /* TAINT not a SOBA-triggerable method for now; must deal with new DB connection without touching
    `%level-db` object in `me`
   */

  this._remove_db = function(db_route, handler) {
    warn("erasing database at " + db_route);
    rmrf.sync(db_route);
    warn("erased database at " + db_route);
    return handler(null);
  };

  this.put = function(me, socket, key, value, handler) {
    var _ref;
    if (handler == null) {
      _ref = [null, value], value = _ref[0], handler = _ref[1];
    }
    return me['%level-db'].put(key, value, handler);
  };

  this.get = function(me, socket, key, handler) {
    throw new Error('not implemented');
  };

  this.dump = function(me, socket, settings) {
    var Z, db, format, input, limit, soba_server, _ref, _ref1;
    format = (_ref = settings != null ? settings['format'] : void 0) != null ? _ref : 'one-by-one';
    limit = (_ref1 = settings != null ? settings['take'] : void 0) != null ? _ref1 : 10;
    db = this.get_level_db(me);
    soba_server = this.get_soba_server(me);
    input = range(db, '');
    switch (format) {
      case 'list':
        Z = [];
        break;
      case 'one-by-one':
        null;
        break;
      default:

        /* TAINT put error on socket??? */
        throw new Error("unknown format " + (rpr(format)));
    }

    /* TAINT how to signal end of stream when `format is 'one-by-one'`? */

    /* TAINT should we identify response with a request ID?
      how do clients sort out responses from overlapping requests`
     */
    return input.pipe(D.$take(limit)).pipe(D.$show()).pipe($((function(_this) {
      return function(facet, send, end) {
        if (facet != null) {
          switch (format) {
            case 'list':
              Z.push(facet);
              break;
            case 'one-by-one':
              SOBA.emit(soba_server, socket, 'dump', facet);
          }
          send(1);
        }
        if (end != null) {
          switch (format) {
            case 'list':
              SOBA.emit(soba_server, socket, 'dump', Z);
              break;
            case 'one-by-one':
              null;
          }

          /* FUTURE */
          return end();
        }
      };
    })(this)));
  };

  this.demo = function(db_route) {
    var db, level_db, router, sio_server;
    db = SBLVL.new_db(db_route);
    level_db = SBLVL.get_level_db(db);
    router = SBLVL.get_socket_router(db);
    router.on('*', (function(_this) {
      return function(socket, P, next) {
        debug('©9kKtv', socket['id'], P);
        return next();
      };
    })(this));
    SOBA.serve(db);
    sio_server = SBLVL.get_sio_server(db);
    return sio_server.on('connection', (function(_this) {
      return function(socket) {
        var sb;
        debug('©81uDb', 'connected');
        sb = SBLVL.get_soba_server(db);

        /* OBS: we're using pipedreams-style method signatures here where payload is always single argument */
        socket.on('get', function(_arg) {
          var key;
          key = _arg[0];
          return SBLVL.get(db, socket, key, function(error) {
            if (error != null) {
              throw error;
            }
            return urge('ready:', 'get', key);
          });
        });

        /* OBS: we're using pipedreams-style method signatures here where payload is always single argument */
        socket.on('put', function(_arg) {
          var key, value;
          key = _arg[0], value = _arg[1];
          return SBLVL.put(db, socket, key, value, function(error) {
            if (error != null) {
              throw error;
            }
            return urge('ready:', 'put', key);
          });
        });
        socket.on('dump', function(settings) {
          return SBLVL.dump(db, socket, settings, function(error) {
            if (error != null) {
              throw error;
            }
            return urge('ready:', 'dump');
          });
        });
        return socket.on('remove-db', function() {
          return SBLVL.dump(db, socket, settings, function(error) {
            if (error != null) {
              throw error;
            }
            return urge('ready:', 'remove-db');
          });
        });
      };
    })(this));

    /*
    router.on 'get', ( socket, P, next ) =>
      debug 'get', P
      next()
    
    router.on 'put', ( socket, P, next ) =>
      debug 'put', P
      next()
     */
  };

  if ((module.parent == null) || __indexOf.call(process.argv, 'serve') >= 0) {
    SBLVL = this;
    db_route = njs_path.join(__dirname, '../../data/mydb');
    SBLVL._remove_db(db_route, function() {
      return SBLVL.demo(db_route);
    });
  }

}).call(this);
